### ISSUE TITLE
CRAN installation error on r-release-macos-x86_64

### ISSUE THREAD

**Issue by appelmar** [appelmar/gdalcubes_R#69]
gdalcubes fails to build on CRAN r-release-macos-x86_64, see https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/gdalcubes-00install.html. Neither the R-hub-builder nor macOS builder can reproduce the bug.  Packages `sf` and `terra` compile without any problems.

**Comment by appelmar** [comment]
Perhaps related: https://stat.ethz.ch/pipermail/r-sig-mac/2022-September/014565.html

**Comment by appelmar** [comment]
@edzer did you have this issue with sf as well? I am getting lots of undefined symbol errors on r-release-macos-x86_64 (maybe because -lzstd is missing there?).

**Comment by edzer** [comment]
Is this new or has this been there a longer time? A possibility is that Simon solved this on the build machine when we noticed it a few months ago it but that gdalcubes was not recompiled at that time? (R is at 4.2.1 since June, this error came from 4.2.0: https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/gdalcubes-00check.html but tagged r-release)

**Comment by appelmar** [comment]
Thanks, you might be right, it is not new, I just found out because I received an email from Oxford today (other issues are rather easy to fix).

**Comment by edzer** [comment]
Ah, the Oxford mail. Yes, resubmitting the package might well fix it!
